version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: guess_game
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
